version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: npm
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: composer
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: swift
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: bundler
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: elm
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: dotnet-sdk
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: gitsubmodule
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: nuget
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: terraform
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope
  - package-ecosystem: pub
    directory: "/"
    schedule:
      interval: weekly
      time: "00:00"
    open-pull-requests-limit: 100
    rebase-strategy: auto
    commit-message:
      prefix: feat
      prefix-development: deps
      include: scope